#ifndef SM_STATE_MACHINE_CONFIG_H_
#define SM_STATE_MACHINE_CONFIG_H_

#ifndef SM_STATE_MACHINE_ENABLE_LOG
#define SM_STATE_MACHINE_ENABLE_LOG 1u
#endif

#endif /* ifndef SM_STATE_MACHINE_CONFIG_H_ */
